import Vue from "vue";
import Vuetify from "vuetify/lib";
import es from "vuetify/es5/locale/es";
import "@fortawesome/fontawesome-free/css/all.css";
Vue.use(Vuetify);
const MY_ICONS = {
  menupts: "fas fa-ellipsis-v",
  barspro: "fas fa-bars",
  notes: "far fa-clipboard",
  users: "fas fa-users",
  user: "fas fa-user",
  users_cog: "fas fa-users-cog",
  config: "far fa-wrench",
  plus: "fas fa-plus",
  minus: "fas fa-minus",
  eye: "far fa-eye",
  edit: "far fa-edit",
  delete: "far fa-trash-alt",
  folder: "fas fa-folder-open",
  newpaper: "fas fa-newspaper",
  home: "fas fa-home",
  phone: "fas fa-phone-square",
  comments: "fas fa-comments",
  sync: "fas fa-sync",
  paper_plane: "fas fa-paper-plane",
  logout: "fas fa-sign-out-alt",
  map: "fas fa-map-marker-alt",
  address: "far fa-address-card",
  mail: "far fa-envelope",
  mail_solid: "fas fa-envelope",
  job: "fas fa-toolbox",
  party: "fas fa-birthday-cake",
  projects: "fas fa-project-diagram",
  act: "fas fa-snowboarding",
  jorn: "fas fa-tasks",
  eye: "far fa-eye",
  clock: "far fa-clock",
  calendar: "far fa-calendar-alt",
  calen_day: "fas fa-calendar-day",
  lang: "fas fa-language",
  dumbbell: "fas fa-dumbbell",
  config: "fas fa-wrench",
  cancel: "fas fa-times",
  medic: "fas fa-notes-medical",
  hand: "fas fa-hand-paper",
  user_cancel: "fas fa-user-times",
  search: "fas fa-search",
  arrow_up: "fas fa-arrow-up",
  arrow_down: "fas fa-arrow-down",
  arrow_right: "fas fa-arrow-right",
  arrow_left: "fas fa-arrow-left",
  angle_down: "fas fa-angle-down",
  angle_right: "fas fa-angle-right",
  angle_left: "fas fa-angle-left",
  check: "fas fa-check",
  facebook: "fab fa-facebook-f",
  twitter: "fab fa-twitter",
  instagram: "fab fa-instagram",
  clipboard: "fas fa-clipboard",
  pdf: "far fa-file-pdf",
  save: "far fa-save",
  shield: "fas fa-shield-alt",
  lock: "fas fa-lock",
  db: "fas fa-database",
  rev: "fab fa-rev",
  sms: "fas fa-envelope",
};
export default new Vuetify({
  theme: {
    options: {
      customProperties: true,
    },
    themes: {
      light: {
        primary: "#1B96B1",
        secondary: "#424242",
        accent: "#82B1FF",
        error: "#FF5252",
        info: "#2196F3",
        success: "#4CAF50",
        warning: "#FFC107",
      },
    },
  },
  lang: {
    locales: {
      es,
    },
    current: "es",
  },
  icons: {
    iconfont: "fa",
    values: MY_ICONS,
  },
});
